openapi: 3.0.3

info:
  title: Score cards OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan score cards service.

tags:
  - name: ScoreCards
    description: CRUD operations for handling score cards.

servers:
  - url: http://localhost:8083/api/

paths:
  /scorecards:
    $ref: "./paths.yaml#/ScoreCards"
  /scorecards/{id}:
    $ref: "./paths.yaml#/ScoreCard"

components:
  schemas:
    Course:
      $ref: "./schemas.yaml#/Course"
    Player:
      $ref: "./schemas.yaml#/Player"
    NewScoreCard:
      $ref: "./schemas.yaml#/NewScoreCard"
    ScoreCard:
      $ref: "./schemas.yaml#/ScoreCard"
    ScoreRow:
      $ref: "./schemas.yaml#/ScoreRow"
    Score:
      $ref: "./schemas.yaml#/Score"
    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
