openapi: 3.0.3

info:
  title: Score cards OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan score cards service.

tags:
  - name: ScoreCards
    description: CRUD operations for handling score cards.
  - name: AddNewScore
    description: Adding a new score to a score card. This is it's own API to make Quarkus code generation work correctly.
  - name: Scores
    description: CRUD operations for handling score rows in a score card.

servers:
  - url: http://localhost:8083

paths:
  /scorecards:
    $ref: "./paths.yaml#/ScoreCards"
  /scorecards/{id}:
    $ref: "./paths.yaml#/ScoreCard"
  /scorecards/{id}/scores:
    $ref: "./paths_add_score.yaml#/AddNewScore"
  /scores/{id}:
    $ref: "./paths_scores.yaml#/Scores"

components:
  schemas:
    Course:
      $ref: "./schemas.yaml#/Course"
    Player:
      $ref: "./schemas.yaml#/Player"
    NewScoreCard:
      $ref: "./schemas.yaml#/NewScoreCard"
    ScoreCard:
      $ref: "./schemas.yaml#/ScoreCard"
    ScoreCardSummary:
      $ref: "./schemas.yaml#/ScoreCardSummary"
    NewScore:
      $ref: "./schemas.yaml#/NewScore"
    PlayerScore:
      $ref: "./schemas.yaml#/PlayerScore"
    PlayerScoreEntry:
      $ref: "./schemas.yaml#/PlayerScoreEntry"
    PlayerScoreSummary:
      $ref: "./schemas.yaml#/PlayerScoreSummary"
    Score:
      $ref: "./schemas.yaml#/Score"
    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
    ValidationErrorBody:
      $ref: "../errors/schemas.yaml#/ValidationErrorBody"
