openapi: 3.0.3

info:
  title: Score cards OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan score cards service.

tags:
  - name: ScoreCards
    description: CRUD operations for handling score cards.
  - name: Scores
    description: CRUD operations for handling score rows in a score card.
  - name: ScoresForHole
    description: CRUD operations for handling score rows by hole number.

servers:
  - url: http://localhost:8083/api/

paths:
  /scorecards:
    $ref: "./paths.yaml#/ScoreCards"
  /scorecards/{id}:
    $ref: "./paths.yaml#/ScoreCard"
  /scorecards/{id}/scores:
    $ref: "./paths.yaml#/AddNewScore"
  /scores/{id}:
    $ref: "./paths_scores.yaml#/Scores"
  /scorecards/{id}/scores/{holeNumber}:
    $ref: "./paths_scores.yaml#/ScoresForHole"

components:
  schemas:
    Course:
      $ref: "./schemas.yaml#/Course"
    Player:
      $ref: "./schemas.yaml#/Player"
    PlayerScore:
      $ref: "./schemas.yaml#/PlayerScore"
    NewScoreCard:
      $ref: "./schemas.yaml#/NewScoreCard"
    ScoreCard:
      $ref: "./schemas.yaml#/ScoreCard"
    ScoreRow:
      $ref: "./schemas.yaml#/ScoreRow"
    NewScore:
      $ref: "./schemas.yaml#/NewScore"
    Score:
      $ref: "./schemas.yaml#/Score"
    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
    ValidationErrorBody:
      $ref: "../errors/schemas.yaml#/ValidationErrorBody"
