openapi: 3.0.3

info:
  title: Queries OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan queries service.

tags:
  - name: QueryCourses
    description: Fetch disc golf courses.
  - name: QueryPlayers
    description: Fetch players.
  - name: QueryScoreCards
    description: Fetch disc golf score cards.

servers:
  - url: http://localhost:8080

paths:
  /courses:
    $ref: "courses/paths.yaml#/Courses"
  /courses/{id}:
    $ref: "courses/paths.yaml#/Course"
  /players:
    $ref: "./paths_players.yaml#/Players"
  /players/{id}:
    $ref: "./paths_players.yaml#/Player"
  /scorecards:
    $ref: "./paths_scorecards.yaml#/ScoreCards"
  /scorecards/{id}:
    $ref: "./paths_scorecards.yaml#/ScoreCard"

components:
  schemas:
    Course:
      $ref: "courses/schemas.yaml#/Course"
    CourseSummary:
      $ref: "courses/schemas.yaml#/CourseSummary"
    Hole:
      $ref: "courses/schemas.yaml#/Hole"
    Player:
      $ref: "./schemas.yaml#/Player"
    Score:
      $ref: "./schemas.yaml#/Score"
    ScoreSummary:
      $ref: "./schemas.yaml#/ScoreSummary"
    ScoreCard:
      $ref: "./schemas.yaml#/ScoreCard"
    ScoreCardSummary:
      $ref: "./schemas.yaml#/ScoreCardSummary"
    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
