version: "3.8"

services:
  openapi:
    command: generate -i /openapi/openapi.yaml -g openapi -o ./generated1
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
      - ./apidoc.json:/generated1/openapi.json

  courses-api:
    command: generate -i /openapi/courses/openapi.yaml -g openapi -o ./generated2
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
      - ./apidoc_courses.json:/generated2/openapi.json

  players-api:
    command: generate -i /openapi/players/openapi.yaml -g openapi -o ./generated3
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
      - ./apidoc_players.json:/generated3/openapi.json

  scorecards-api:
    command: generate -i /openapi/scoreCards/openapi.yaml -g openapi -o ./generated4
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
      - ./apidoc_scorecards.json:/generated4/openapi.json

  scorecard-aggregates-api:
    command: generate -i /openapi/scoreCardAggregates/openapi.yaml -g openapi -o ./generated5
    image: openapitools/openapi-generator-cli
    volumes:
      - ./openapi:/openapi
      - ./apidoc_scorecard_aggregates.json:/generated5/openapi.json
