openapi: 3.0.3

info:
  title: Kiskotaan OpenAPI
  version: 0.2.0
  description: API definition for Kiskotaan disc golf score card application.

tags:
  - name: QueryCourses
    description: Fetch courses. API not used currently.
  - name: QueryPlayers
    description: Fetch players. API not used currently.
  - name: QueryScoreCards
    description: Fetch score cards. API not used currently.
  - name: Courses
    description: CRUD operations for handling courses.
  - name: Holes
    description: CRUD operations for handling a course's holes.
  - name: Players
    description: CRUD operations for handling players.
  - name: ScoreCards
    description: CRUD operations for handling score cards.
  - name: AddNewScore
    description: Adding a new score to a score card. This is it's own API to make Quarkus code generation work correctly.
  - name: Scores
    description: CRUD operations for handling score rows in a score card.

servers:
  - url: http://localhost:8080

paths:
  /query/courses:
    $ref: "queries/courses/paths.yaml#/Courses"
  /query/courses/{id}:
    $ref: "queries/courses/paths.yaml#/Course"
  /query/players:
    $ref: "queries/players/paths.yaml#/Players"
  /query/players/{id}:
    $ref: "queries/players/paths.yaml#/Player"
  /query/scorecards:
    $ref: "queries/scorecards/paths.yaml#/ScoreCards"
  /query/scorecards/{id}:
    $ref: "queries/scorecards/paths.yaml#/ScoreCard"

  /courses:
    $ref: "./courses/paths.yaml#/Courses"
  /courses/{id}:
    $ref: "./courses/paths.yaml#/Course"
  /courses/{id}/holes:
    $ref: "./courses/paths.yaml#/AddNewHole"
  /holes/{id}:
    $ref: "./courses/paths_holes.yaml#/Hole"

  /players:
    $ref: "./players/paths.yaml#/Players"
  /players/{id}:
    $ref: "./players/paths.yaml#/Player"

  /scorecards:
    $ref: "./scoreCards/paths.yaml#/ScoreCards"
  /scorecards/{id}:
    $ref: "./scoreCards/paths.yaml#/ScoreCard"
  /scorecards/{id}/scores:
    $ref: "./scoreCards/paths_add_score.yaml#/AddNewScore"
  /scores/{id}:
    $ref: "./scoreCards/paths_scores.yaml#/Scores"

components:
  schemas:
    NewCourse:
      $ref: "./courses/schemas.yaml#/NewCourse"
    Course:
      $ref: "./courses/schemas.yaml#/Course"
    NewCourseName:
      $ref: "./courses/schemas.yaml#/NewCourseName"
    CourseName:
      $ref: "./courses/schemas.yaml#/CourseName"
    CourseSummary:
      $ref: "./courses/schemas.yaml#/CourseSummary"

    NewHole:
      $ref: "./courses/schemas.yaml#/NewHole"
    Hole:
      $ref: "./courses/schemas.yaml#/Hole"
    HoleDetails:
      $ref: "./courses/schemas.yaml#/HoleDetails"

    NewPlayer:
      $ref: "./players/schemas.yaml#/NewPlayer"
    Player:
      $ref: "./players/schemas.yaml#/Player"

    NewScoreCard:
      $ref: "./scoreCards/schemas.yaml#/NewScoreCard"
    ScoreCard:
      $ref: "./scoreCards/schemas.yaml#/ScoreCard"
    ScoreCardSummary:
      $ref: "./scoreCards/schemas.yaml#/ScoreCardSummary"
    NewScore:
      $ref: "./scoreCards/schemas.yaml#/NewScore"
    PlayerScore:
      $ref: "./scoreCards/schemas.yaml#/PlayerScore"
    PlayerScoreSummary:
      $ref: "./scoreCards/schemas.yaml#/PlayerScoreSummary"
    Score:
      $ref: "./scoreCards/schemas.yaml#/Score"

    ErrorBody:
      $ref: "./errors/schemas.yaml#/ErrorBody"
    ValidationErrorBody:
      $ref: "./errors/schemas.yaml#/ValidationErrorBody"
