openapi: 3.0.3

info:
  title: Kiskotaan OpenAPI
  version: 0.2.0
  description: API definition for Kiskotaan disc golf score card application.

tags:
  - name: Courses
    description: CRUD operations for handling courses.
  - name: Holes
    description: CRUD operations for handling a course's holes.
  - name: Players
    description: CRUD operations for handling players.
  - name: Game
    description: Operations for starting and ending a game.
  - name: ScoreCards
    description: CRUD operations for handling score cards.

servers:
  - url: http://localhost:8080/api/

paths:
  /courses:
    $ref: "./courses/paths.yaml#/Courses"
  /courses/{id}:
    $ref: "./courses/paths.yaml#/Course"
  /courses/{id}/holes:
    $ref: "./courses/paths.yaml#/AddNewHole"
  /holes/{id}:
    $ref: "./courses/paths_holes.yaml#/Hole"

  /players:
    $ref: "./players/paths.yaml#/Players"
  /players/{id}:
    $ref: "./players/paths.yaml#/Player"

  /games:
    $ref: "./games/paths.yaml#/Games"
  /games/{id}:
    $ref: "./games/paths.yaml#/Game"

  /scoreCards:
    $ref: "./scoreCards/paths.yaml#/ScoreCards"
  /scoreCards/{id}:
    $ref: "./scoreCards/paths.yaml#/ScoreCard"
  /scoreCards/{id}/scores:
    $ref: "./scoreCards/paths.yaml#/Scores"

components:
  schemas:
    NewCourse:
      $ref: "./courses/schemas.yaml#/NewCourse"
    Course:
      $ref: "./courses/schemas.yaml#/Course"
    NewCourseName:
      $ref: "./courses/schemas.yaml#/NewCourseName"
    CourseName:
      $ref: "./courses/schemas.yaml#/CourseName"
    CourseSummary:
      $ref: "./courses/schemas.yaml#/CourseSummary"

    NewHole:
      $ref: "./courses/schemas.yaml#/NewHole"
    Hole:
      $ref: "./courses/schemas.yaml#/Hole"

    NewPlayer:
      $ref: "./players/schemas.yaml#/NewPlayer"
    Player:
      $ref: "./players/schemas.yaml#/Player"

    Game:
      $ref: "./games/schemas.yaml#/Game"
    NewGame:
      $ref: "./games/schemas.yaml#/NewGame"

    NewScoreCard:
      $ref: "./scoreCards/schemas.yaml#/NewScoreCard"
    ScoreCard:
      $ref: "./scoreCards/schemas.yaml#/ScoreCard"
    ScoreRow:
      $ref: "./scoreCards/schemas.yaml#/ScoreRow"
    Score:
      $ref: "./scoreCards/schemas.yaml#/Score"

    ErrorBody:
      $ref: "./errors/schemas.yaml#/ErrorBody"
