openapi: 3.0.3

info:
  title: Courses OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan courses service.

tags:
  - name: Courses
    description: CRUD operations for handling courses.

servers:
  - url: http://localhost:8082

paths:
  /courses:
    $ref: "./paths.yaml#/Courses"
  /courses/{id}:
    $ref: "./paths.yaml#/Course"
  /courses/{id}/holes:
    $ref: "./paths_holes.yaml#/Holes"
  /courses/{id}/holes/{number}:
    $ref: "./paths_holes.yaml#/Hole"

components:
  schemas:
    NewCourse:
      $ref: "./schemas.yaml#/NewCourse"
    Course:
      $ref: "./schemas.yaml#/Course"
    NewCourseName:
      $ref: "./schemas.yaml#/NewCourseName"
    CourseName:
      $ref: "./schemas.yaml#/CourseName"
    CourseSummary:
      $ref: "./schemas.yaml#/CourseSummary"
    UpdatedHole:
      $ref: "./schemas.yaml#/UpdatedHole"
    Hole:
      $ref: "./schemas.yaml#/Hole"
    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
    ValidationErrorBody:
      $ref: "../errors/schemas.yaml#/ValidationErrorBody"
