openapi: 3.0.3

info:
  title: Kiskotaan OpenAPI
  version: 0.2.0
  description: API definition for Kiskotaan score cards aggregation service.

tags:
  - name: ScoreCardAggregates
    description: Read queries for aggregated score card info.

servers:
  - url: http://localhost:8084/api/

paths:
  /scorecards/query/{id}:
    $ref: "./paths.yaml#/ScoreCard"

components:
  schemas:
    Course:
      $ref: "../courses/schemas.yaml#/Course"
    Hole:
      $ref: "../courses/schemas.yaml#/Hole"

    Player:
      $ref: "../players/schemas.yaml#/Player"

    ScoreCard:
      $ref: "./schemas.yaml#/ScoreCard"
    Score:
      $ref: "./schemas.yaml#/Score"

    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
