openapi: 3.1.0

info:
  title: Games OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan games service.

tags:
  - name: Games
    description: Operations for starting and ending a game.

servers:
  - url: http://localhost:8084

paths:
  /games:
    $ref: "paths.yaml#/Games"
  /games/{id}:
    $ref: "paths.yaml#/Game"

components:
  schemas:
    Game:
      $ref: "schemas.yaml#/Game"
    NewGame:
      $ref: "schemas.yaml#/NewGame"
    ErrorBody:
      $ref: "../errors/schemas.yaml#/ErrorBody"
    ValidationErrorBody:
      $ref: "../errors/schemas.yaml#/ValidationErrorBody"
