# Workflow for development branch.
# Checks that the generated code compiles.

name: Development branch workflow

on:
  push:
    branches-ignore:
      - master
      - release*

jobs:
  build:
    name: Maven package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build and test with Maven
        run: mvn -B clean package

  clean_packages:
    name: Clean old packages stored in GitHub
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Clean old artifacts
        uses: actions/delete-package-versions@v1
        with:
          package-name: kiskotaan-openapi
          num-old-versions-to-delete: 3