# Builds the openapi.json schema by using Docker Compose
name: Feature branch workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build openapi.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up
