# Workflow for master branch.
#
# The workflow executes the following jobs:
#   1) Package the generated code as jar.
#   2) Publish a new Maven release.
#   3) Push the generated artifact to GitHub Packages.
#   4) Delete three oldest build artifacts from GitHub Packages.

name: Master branch workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Maven package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build and test with Maven
        run: mvn -B clean package

  release:
    name: Maven release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          git-release-bot-name: release-bot
          git-release-bot-email: release-bot@example.com
          maven-repo-server-id: github
          maven-repo-server-username: mika-alaoutinen
          maven-repo-server-password: ${{ secrets.ACCESS_TOKEN }}
          release-branch-name: master

  clean_packages:
    name: Clean old packages stored in GitHub
    runs-on: ubuntu-latest
    needs:
      - release
    steps:
      - name: Use Node.js 12.x
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Clean old artifacts
      - uses: actions/delete-package-versions@v1
        with:
          package-name: kiskotaan-openapi
          num-old-versions-to-delete: 3