# Builds the OpenAPI documents by using Docker Compose and pushes them to the master branch.
name: Master branch workflow

on:
  push:
    branches:
      - master

jobs:
  update-schema:
    name: Update openapi.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated API documents.
          file_pattern: "apidoc*"
