# Workflow for master branch.
#
# Executes the following jobs:
#   1) Package the code as jar.
#   2) Create new Maven release.
#   3) Push jar to GitHub Packages.

name: Master branch workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Maven package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Build and test with Maven
        run: mvn -B clean package

  release:
    name: Maven release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: master
          git-release-bot-name: release-bot
          git-release-bot-email: release-bot@example.com
          access-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish jar package on GitHub Packages
    runs-on: ubuntu-latest
    needs:
      - build
      - release
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 1.14
      - name: Maven deploy
        run: mvn -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
