openapi: 3.0.3
 
info:
  title: Kiskotaan OpenAPI
  version: 0.1.0
  description: API definition for Kiskotaan disc golf score card application.

tags:
  - name: Courses
    description: CRUD operations for handling the courses registered in the application.
  - name: Players
    description: CRUD operations for handling the players registered in the application.
  - name: Game
    description: Operations for starting and ending a game.
  - name: ScoreCards
    description: Operations for adding, updating and deleting score cards.

servers:
  - url: http://localhost:8080/api/
 
components:
  schemas:
    NewCourseResource:
      $ref: "./schemas.yaml#/NewCourseResource"
    NewPlayerResource:
      $ref: "./schemas.yaml#/NewPlayerResource"
    NewScoreCardResource:
      $ref: "./schemas.yaml#/NewScoreCardResource"
    CourseResource:
      $ref: "./schemas.yaml#/CourseResource"
    ErrorResource:
      $ref: "./schemas.yaml#/ErrorResource"
    GameResource:
      $ref: "./schemas.yaml#/GameResource"
    HoleResource:
      $ref: "./schemas.yaml#/HoleResource"
    PlayerResource:
      $ref: "./schemas.yaml#/PlayerResource"
    ScoreCardResource:
      $ref: "./schemas.yaml#/ScoreCardResource"
    ScoreCardIdResource:
      $ref: "./schemas.yaml#/ScoreCardIdResource"
    ScoreRowResource:
      $ref: "./schemas.yaml#/ScoreRowResource"
    ScoreResource:
      $ref: "./schemas.yaml#/ScoreResource"

paths:
  /courses:
    $ref: "./paths.yaml#/Courses"

  /players:
    $ref: "./paths.yaml#/Players"
  /players/{id}:
    $ref: "./paths.yaml#/Player"

  /games:
    $ref: "./paths.yaml#/Games"
  /games/{id}:
    $ref: "./paths.yaml#/Game"
  
  /scoreCards:
    $ref: "./paths.yaml#/ScoreCards"
  /scoreCards/{id}:
    $ref: "./paths.yaml#/ScoreCard"
  /scoreCards/{id}/scores:
    $ref: "./paths.yaml#/Scores"